{{- if and .Values.cache.purgeToken (not .Values.cache.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssr-knative.purgeSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ssr-knative.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.cache.existingSecretKey }}: {{ .Values.cache.purgeToken | quote }}
{{- end }}
