package main

import (
	"encoding/json"
	"flag"
	"net/http"
	"os"
	"testing"
)

// Generates the canonical cache-key vectors published in spec/key-vectors.json.
//
// This repo owns the key format, because the edge proxy is the one component
// every deployment runs regardless of framework. Adapters (SvelteKit today,
// others later) are consumers: their CI asserts their own key builder against
// this file, so a divergence fails the adapter's build, which is where the bug
// would be.
//
// Regenerate after any change to the format:
//
//	go test ./... -run TestSpecVectors -update
//
// and bump SpecVersion so consumers fail loudly rather than silently reading a
// namespace nobody writes to.

var update = flag.Bool("update", false, "regenerate spec/key-vectors.json")

const specPath = "../spec/key-vectors.json"

// SpecVersion is the cache-key format version. Any change to key construction,
// query normalisation, vary hashing or auth detection must bump this.
const SpecVersion = 1

type spec struct {
	Version int          `json:"version"`
	Note    string       `json:"note"`
	Keys    []keyVector  `json:"keys"`
	Vary    []varyVector `json:"vary"`
	Auth    []authVector `json:"auth"`
}

type keyVector struct {
	Name  string `json:"name"`
	Input struct {
		Prefix   string   `json:"prefix"`
		Version  string   `json:"version"`
		Segment  string   `json:"segment"`
		Host     string   `json:"host"`
		Method   string   `json:"method"`
		Pathname string   `json:"pathname"`
		RawQuery string   `json:"rawQuery"`
		Ignored  []string `json:"ignored"`
	} `json:"input"`
	NormalisedQuery string `json:"normalisedQuery"`
	Key             string `json:"key"`
}

type varyVector struct {
	Name        string            `json:"name"`
	Headers     map[string]string `json:"headers"`
	VaryHeaders []string          `json:"varyHeaders"`
	Hash        string            `json:"hash"`
}

type authVector struct {
	Cookie        string   `json:"cookie"`
	AuthCookies   []string `json:"authCookies"`
	Authenticated bool     `json:"authenticated"`
}

var specIgnored = []string{"utm_source", "utm_medium", "gclid", "fbclid", "ref"}

var specAuthCookies = []string{"auth_token", "access_token", "refresh_token", "authToken", "session"}

func buildSpec() spec {
	cases := []struct{ name, pathname, query string }{
		{"root", "/", ""},
		{"simple path", "/airing", ""},
		{"show detail", "/show/12345", ""},
		{"sorted params", "/search", "z=1&a=2&m=3"},
		{"duplicate keys sorted by value", "/search", "tag=b&tag=a&tag=c"},
		{"tracking params stripped", "/", "utm_source=twitter&q=naruto&gclid=xyz"},
		{"only tracking params", "/", "utm_source=x&fbclid=y"},
		{"space encoding", "/search", "q=cowboy bebop"},
		{"plus is a space", "/search", "q=cowboy+bebop"},
		{"punctuation unreserved by encodeURIComponent", "/search", "q=a!b~c*d'e(f)g"},
		// Semicolons: url.ParseQuery drops these, URLSearchParams keeps them.
		{"reserved punctuation", "/search", "q=a/b:c@d,e;f=g"},
		{"unicode japanese", "/search", "q=カウボーイビバップ"},
		{"emoji", "/search", "q=🍿"},
		{"empty value", "/search", "q="},
		{"ampersand in value", "/search", "q=fate%26stay"},
		{"path with encoded chars", "/show/some%20title", ""},
	}

	ignored := map[string]bool{}
	for _, p := range specIgnored {
		ignored[p] = true
	}

	s := spec{
		Version: SpecVersion,
		Note: "Canonical cache-key vectors. Generated by edge/vectors_test.go in " +
			"weeb-vip/knative-ssr. Adapters assert their key builder against this file.",
	}

	for _, c := range cases {
		for _, segment := range []string{SegmentPublic, SegmentAnon, SegmentAuth} {
			query := normaliseQuery(c.query, ignored)

			kb := keyBase{
				Prefix: "ssr", Version: "1.98.0", Host: "staging.weeb.vip",
				Method: "GET", Pathname: c.pathname, Query: query, VaryHash: "0",
			}

			v := keyVector{Name: c.name + " [" + segment + "]", NormalisedQuery: query, Key: kb.key(segment)}
			v.Input.Prefix = "ssr"
			v.Input.Version = "1.98.0"
			v.Input.Segment = segment
			v.Input.Host = "staging.weeb.vip"
			v.Input.Method = "GET"
			v.Input.Pathname = c.pathname
			v.Input.RawQuery = c.query
			v.Input.Ignored = specIgnored

			s.Keys = append(s.Keys, v)
		}
	}

	varyCases := []struct {
		headers     map[string]string
		varyHeaders []string
	}{
		// Empty slice, not nil: a nil marshals to `null`, and a consumer reading
		// `null.length` crashes rather than seeing "no vary headers".
		{map[string]string{}, []string{}},
		{map[string]string{"accept-language": "en-GB"}, []string{"accept-language"}},
		{map[string]string{"accept-language": "ja"}, []string{"accept-language"}},
		{map[string]string{}, []string{"accept-language"}},
		{map[string]string{"accept-language": "en", "x-device": "mobile"}, []string{"X-Device", "accept-language"}},
	}

	for i, c := range varyCases {
		h := http.Header{}
		for k, v := range c.headers {
			h.Set(k, v)
		}
		if c.headers == nil {
			c.headers = map[string]string{}
		}
		s.Vary = append(s.Vary, varyVector{
			Name:        "vary " + string(rune('0'+i)),
			Headers:     c.headers,
			VaryHeaders: c.varyHeaders,
			Hash:        varyHash(h, c.varyHeaders),
		})
	}

	authCases := []string{
		"", "theme=dark", "auth_token=abc123", "theme=dark; auth_token=abc123",
		"auth_token=", "auth_token=null", "auth_token=undefined", "auth_token=deleted",
		"guest_access_token=x", "session=xyz", "  refresh_token = spaced  ", "malformed;;;auth_token=ok",
	}

	for _, cookie := range authCases {
		r := &http.Request{Header: http.Header{}}
		if cookie != "" {
			r.Header.Set("Cookie", cookie)
		}
		s.Auth = append(s.Auth, authVector{
			Cookie:        cookie,
			AuthCookies:   specAuthCookies,
			Authenticated: isAuthenticated(r, specAuthCookies),
		})
	}

	return s
}

func TestSpecVectors(t *testing.T) {
	generated := buildSpec()

	encoded, err := json.MarshalIndent(generated, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	encoded = append(encoded, '\n')

	if *update {
		if err := os.WriteFile(specPath, encoded, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %d key, %d vary, %d auth vectors to %s",
			len(generated.Keys), len(generated.Vary), len(generated.Auth), specPath)
		return
	}

	committed, err := os.ReadFile(specPath)
	if err != nil {
		t.Fatalf("read spec (regenerate with: go test ./... -run TestSpecVectors -update): %v", err)
	}

	if string(committed) != string(encoded) {
		t.Error("spec/key-vectors.json is stale — regenerate with:\n" +
			"  go test ./... -run TestSpecVectors -update\n" +
			"and bump SpecVersion if the key format itself changed.")
	}
}
